version: '3'
services:

  bot:
    build: ../../../
    environment:
      - BOT_DEBUG=${TELEGRAM_BOT_DEBUG}
      - BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - BOT_NEO4J=neo4j://localhost:7687

  # Default HTTP port is 7474
  # Default BOLT port is 7687
  neo4j:
    image: neo4j:4.2
    environment:
      - NEO4J_AUTH=none
