version: '3'
services:

  # Default HTTP port is 7474
  # Default BOLT port is 7687
  neo4j:
    image: neo4j:4.2
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "7687:7687"

      # Default port is 27017
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
